=== Kashyap-10/KavachX-Assesment/event_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "KavachXEvent",
  "type": "object",
  "properties": {
    "event_id": {
      "type": "string",
      "description": "Unique UUID for the event"
    },
    "device_id": {
      "type": "string",
      "description": "Edge device identifier",
      "default": "kx-edge-001"
    },
    "camera_id": {
      "type": "string",
      "description": "Camera identifier",
      "default": "cam-03"
    },
    "rule_id": {
      "type": "string",
      "description": "Identifier for the violated rule"
    },
    "rule_text": {
      "type": "string",
      "description": "Original plain-English rule"
    },
    "ts_start": {
      "type": "string",
      "format": "date-time",
      "description": "ISO-8601 timestamp when tracking began in zone"
    },
    "ts_end": {
      "type": "string",
      "format": "date-time",
      "description": "ISO-8601 timestamp when violation threshold was triggered"
    },
    "track_id": {
      "type": "integer",
      "description": "Track ID of the detected subject"
    },
    "label": {
      "type": "string",
      "description": "Class label (e.g. person)"
    },
    "attributes": {
      "type": "object",
      "description": "Visual attributes of the target (e.g. carrying bag)"
    },
    "confidence": {
      "type": "number",
      "description": "Model detection confidence score between 0.0 and 1.0"
    },
    "dwell_s": {
      "type": "number",
      "description": "Total dwell duration in seconds inside the zone"
    },
    "zone": {
      "type": "string",
      "description": "Identifier of the zone where rule was triggered"
    },
    "evidence_frame": {
      "type": "string",
      "description": "Base64 encoded JPEG with faces/heads masked"
    },
    "needs_verification": {
      "type": "boolean",
      "description": "Flag set to true when detection confidence is borderline"
    }
  },
  "required": [
    "event_id",
    "device_id",
    "camera_id",
    "rule_id",
    "rule_text",
    "ts_start",
    "ts_end",
    "track_id",
    "label",
    "attributes",
    "confidence",
    "dwell_s",
    "zone",
    "evidence_frame",
    "needs_verification"
  ]
}

=== Kashyap-10/KavachX-Assesment/task1/outputs/mot17_bag_demo/event_008cdc4a-565f-419d-9cd7-9d019cd895d5.json
{
  "event_id": "008cdc4a-565f-419d-9cd7-9d019cd895d5",
  "device_id": "kx-edge-001",
  "camera_id": "cam-03",
  "rule_id": "walkway_person_bag_dwell_gt_10s",
  "rule_text": "Alert me if a person carrying a bag enters the walkway and stays more than 10 seconds.",
  "ts_start": "2026-10-26T12:54:47.539478+00:00",
  "ts_end": "2026-10-26T12:54:57.839478+00:00",
  "track_id": 244,
  "label": "person",
  "attributes": {
    "carrying": "bag"
  },
  "confidence": 0.11015526205301285,
  "dwell_s": 10.1,
  "zone": "walkway",
  "evidence_frame": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAIcA8ADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD6ePSoJakLcVDI1dbRwkD9aQdKVutKorOQ0IoqWMc0irUsa81zyBk8Iq1GOKhiXpVpFrnkKwxxxVK5HWtBxxVK5XrWTNIIyLkdazbjvWrdL1rMuV61DO6kjLuOpqlMav3C81QnFK51xKchpiGnyiolPNUhssZ+Wqs54NTlvlqrO3BrRGTKU/eqFxVyZutUp2rRGTKclU7npVyQ1UuSMU7kGZKPmpFp0v3qaDUtisK/Sq0pqd24qrK1JDIJjxVOQ81PM9U5H5rVITY7NOQ1Bup0bc1ViS9FV6Cs+A1ft6lgW4xU4HFRRdqsL0qLisQutQyCrTYqCSqTFYpyiqzDmrctVn+9VpkNDcU4UlKKtCJo6tQ1VjqzFTYi9DVlelVYTVlDxWbGhDVeepyarz1mUjPuu9ZtzWpcjis64FaRBmXcdahT7/4VZnWq+MGtESx1FAOe1OC5piCP74qxUKpgg5qUGpY0LSr1pKVetIZKlWYarJVmGkJlyKrMdVoqsx0MRMtOFNWnCkIUU4UgpwFIkUU4UgFOApAKKcKAKcBQACl7UoFGKAGNTaeRTcUrgNNMapSKYwouMiNMfpUpFMcUFIqyCq8oq04qCUUXKRUI5oIp7DmmGncohkqFqmkNQMaBMQmmk0E03NSyR61NF1qFKsRDmpuJl237Vs2v/Huv+e9ZNsvStS3ZgoXAwKlsET0U5Fz1qTylx1NK4yGipfLHqajcY6UXAqagMqn41lzrWpc5fAIHFUpY6uLFYzWU5NRFfmq+0VRGI7ulaKQrDI1q7bDmo0j9qtW6c0XBou2wrStxVG3XFX4BUNktF+DpV2HpVOHtVyHpWMmTYeahkqY1DJ0qLmkUVJaz7j71aE1Z9wOTTudUCpLUDVNN1qBjzTOmLJoa07PtWVD1rTszyKxqGyZvWQ4Fa1sOKx7JuBWvbHivLrJ3NIlnFNYcUueaRjXLysGV5ulUpOtXJzxVKQ8100kzCRG1JH1pGNLGOa7YvQxZZTpTqSMcU/bQ2Kx6TvprGmg0yaVYomkcnavpX1VecKNOVSo7RSu29kluzyoRc5KMdWx2OaljWs4apbg/cl/If41KmsWi9Y5v++R/jXzM+Lcle2Jieisqxn/PtmkqVNGnNZi65ZD/AJZz/wDfI/xqRNfsV/5ZXH/fI/xrCXFeTP8A5iIlf2Xi/wDn2zaiSrCpxWIniXTx/wAsbn/vlf8AGnjxRp3/ADxuv++V/wDiqxfFOT/9BER/2Vi/+fbNd1qncL1qm3ifTz/yxuv++V/xqCXxDYt0iuP++V/xrKXFGUf9BETSOV4pfYYXSday7letWJtYtX6RzfiB/jVOa9hfor/iB/jWL4nyn/n/ABOmGX4lfYZQuV61nXArSmYP0z+NU5beR+hX8aX+s2Vf8/4m6wWI/kZlzd6rZxWnLp87dHj/ADP+FVzpN12kh/M/4VpHifKf+f8AETwWI/kZUeTAqlcy8HmtV9HvT0kg/wC+j/hVWXw/fv0ltv8Avpv8K1XFGUf9BETJ4DE/yMxJpapyyVvSeF9SbpPa/wDfbf8AxNQP4R1Rv+W9n/323/xNV/rTk/8A0ERJ/s/E/wAjOfeSq078V0p8G6qf+Xiz/wC+2/8Aiajk8Fasw4uLL/vtv/iaX+tOUf8AQREX9nYn+RnHyNzUZausfwFrJP8Ax82H/fb/APxNMPgDWv8An5sP+/j/APxNL/WnKP8AoIiL+zsT/IzkpXqnM9do/wAPdbbpdaf/AN/H/wDiagf4ba83S703/v4//wARVrinJ/8AoIiJ5div5GcNM9VHbmu9f4Y+IG/5fNM/7+v/APEVEfhZ4hJ/4/NL/wC/sn/xFaLirJv+giJP9nYr+RnDA1JGea7YfCzxAP8Al80v/v7J/wDEU9Phfr4PN5pn/fx//iKb4ryb/oIiH9nYr+RnJQHpWjbGujj+Guur/wAvem/9/H/+Iq1F8PtaTrdaf/38f/4ms3xVk/8A0ERH/ZuK/kZz8Rqwp4roE8Cauv8Ay82P/fb/APxNSjwRq3/PxZf99t/8TUf605R/0ERD+zcV/IzmXNV5DXWN4H1c/wDLxY/99t/8TUbeA9YP/LzYf99v/wDE01xTlH/QREn+zcV/IzjpTVVz81dq/wAPtaP/AC9af/38f/4moj8OtbJz9q07/v4//wARWi4qyf8A6CIkvLcX/Izj805a64fDrW/+frT/APv4/wD8TT1+Hmsj/l60/wD7+P8A/E1a4ryb/oIiT/ZmL/59s5SMVZirpl8AawP+Xmw/77f/AOJqZPAmrDrcWP8A32//AMTR/rXk3/QREX9mYv8A59s56GrKHit5PBOqr1uLL/vtv/iakXwbqY/5b2f/AH23/wATUPirJ/8AoIiNZZi/+fbOcNQyjNdSfBuqE/6+z/77b/4mmt4L1Q/8vFn/AN9t/wDE1H+tOT/9BES1luK/kZxk61QnWu7k8C6s3S4sf++2/wDiaryfD/WG6XNh/wB9v/8AE1S4qyf/AKCIh/ZuK/kZ57MlV2jr0KT4ca23S607/v4//wARUR+Gmuf8/em/9/H/APiKtcWZP/0ERE8sxX8jOBCU9Vruv+FZ65/z96b/AN/H/wDiKUfDTXP+fvTf+/j/APxFP/WzJv8AoIiT/ZmL/wCfbOG20Yruv+Faa5/z96b/AN/H/wDiKQ/DTXP+fvTf+/j/APxFL/WvJ/8AoIiH9mYv/n2ziFFOArth8NNc/wCfvTf+/j//ABFOHw21z/n607/v4/8A8RS/1ryf/oIiH9mYv/n2zjEFWYhXWr8OdbH/AC9ad/38f/4ipU+Husr1utP/AO/j/wDxNH+teT/9BEQ/szF/8+2cxEKsxiukTwFq4/5ebH/vt/8A4mpV8D6sP+Xiy/77b/4ml/rXk/8A0ERF/ZmL/wCfbObFOFdKPBOq/wDPxZf99t/8TTh4K1T/AJ+LL/vtv/iaP9asn/6CIi/svF/8+2c2KeBXRjwZqg/5b2f/AH23/wATSjwbqf8Az3s/++2/+Jpf61ZP/wBBERf2Xi/+fbOdAp4FdCPB+p/897P/AL7b/wCJpR4Q1L/nvaf99t/8TS/1qyf/AKCIh/ZeL/59s58CnAV0A8I6j/z3tP8Avtv/AImnDwnqP/Pa0/76b/4ml/rVk/8A0ERD+y8X/wA+2c+BS4roB4U1D/nta/8AfTf/ABNL/wAIpqP/AD2tf++m/wDiaP8AWrJ/+giIf2Xi/wDn2znCKbtq5f2stndyW0wG9Dg4OQe4P5VXxXuU6sKsFUg7pq6fdM4pRcW4y3RGRTWWpcU1hV3EiErUTip2qKSkWis4qvKKsvVeSgsrsKiep3qCQ0wK8pqq7c1YmNU5DTJYpakBqJmpUNJklqOrcA5qpCav2ozioYi/bLWjbrVS2XpWjCtZtlIkjFSkcUItPI4qblERFRyLVjFMZadwsUZEqB4s1osmaYYqpMLGY0PtURh+bpWq0VQmLnpVKQWKixVPDHzUwi9qkjjp8wrD4Vq7CKgiXFWohUtisWIu1XIulVIqtR9KzkxcpITUcnSnk1G5qDSMStMOtUJ15rQl71TmFO5tEzplquy81dmWoCtO5tFjIlOa0rMciqcSc1o2icis5mqZrWWcCte26Vm2S8Cta2XiuScLmiZJTXqbbUco4rH2QORTnPBqlI3NWro4BrOmfBNaxhYybFLipI25qiZOakjkpt2IaNWJxipNwqjFJxUvmVk5DselrUGqf8g+T8P5irCiotVH/Eul/D+Yr6LiP/kUYr/r3P8A9JZ52X/71T/xL80WNPXNrB/1zX+VaUCVU0xM2cB/6Zr/ACrUhSng/wDdKX+GP5IdVfvZerBUqaNMGnKtOUVUmKw9BT+1NFBNYtjuNeqk/erDtVWZqwnI1gyhc96yrvpWpcnrWTeNwa5JM64GTdnrWRdt1rTvH61iXj8mkjYpXL9azppKsXUnXms2eTrXTTRlIbNL71QuJfenTy+9UJ5OtdUUYsJJKgZ6Y71EWpsRIWqORuKYWpjtxUMdiKRuagkanyNzVWV6EgYyd6pyPUkz1WY81rFGbBjmmgU4DNPVa1RDERaljHNKiVKiVLGh8VXIjVZBipkOKzaKLkbVMGqmjVMjVm0IlY8VE9OJ4phqkSyJxUWzmrBFKkeTVozZGkdTxx1LHF7VZih9q0RDIEjqdI6spB7VMsHtTArxpUoWrCQnHSlMXtUMaKjDmo3FWnTBqF1rNo0RTlFVJRV2YVVkFNDKUq1AVq3IKixVCZDsoCVOFpQtMlkGykMdWQlLspXEVglPCVOEpwSi4ESpU0a05VqRVpXEKgqdajUVItADxTxTBTxSEPFPFMFOBpASCnio1NSKaQrDwKeBTAaeDSYxacjMjh0YqynIIOCDTc0ZqWk1Zi2N3xkiveW95Eo8qeEFXAxuI9e/Qr1rBrf1f/SPCum3T8PGxiAHTHI/P5B+tc+TXg8NNxwCovem5Q/8Bk0vwsd2ZK9dzX2kn96uBprUtIxr3ziRE1QS1M5qCU0Foheq71K5qBzQURvVeQ1LIarStTQEExqlKaszNVGZqZDGM1OjbmoGanRtzSJNG3bmtOz7Vj27citWzPIqGBtWvatGCsy1PStKA8Vmy0WVp9MWnZqSgxQRRmloGM20bKkAp6rQBA0fFRGLnpWh5fHSmeVz0qkBT8r2p6x1bEPtT1h9qYisiVMi1MsPtTxHSYDIxVmPpTFTFSqMCoY0hDTGNOY1GxqS0iOSq0oqw5qFxQWinKvFQ7atyCottBaGRLzWlaJyKqRJzWlZpyKk0TNOzTgVq268VStE4HFatuny1PKVcTbUUy8Vc2e1QzpxS5EJyMe7HBrKn6mtm8Xg1j3PBNJoVyo33qkSoXPzU9GrCQF6EcCpcVWhfipvMrnaKPVkFRauP+JZN/wH/wBCFWFFU/EI/wBAT/rqP5Gvf4qq+yybFStf3JL71b9Tz8shzYumvNfgaulL/oNv/wBcl/kK1YVqrAOauxCuyFL2NGNK9+VJfciHLnk5dx+OKOlOPSo2NYTZVhS3FMZ6Y71DJJXPKQrD5HqrM/vSSSVVlkrnnM1giK5fism8frV24k96yL2TrzXPe51wRm3z9aw72Tk1o30nWsK9l5NaRRsU7qXrWZcSe9T3MnXms24krrpozkRzye9UpXzT5Xqs5rpSMWDNUZalbpUbGhkilqid6a7YqCST3qbDuEr1UmellkqnNJVqJLYSvUW6o5JKRG5rVIhstR81PGtV4jVqOgkljWpglNjqYCoZSGhacBTsUhFSxjlqVTUIp4qWgJgeKAeaYDxTl600jOTJFGasQx5PSmQrk1oWsWSOKpIzYsMGe1Xobb2qxa2+ccVq21pnHFUiTOitM9qmW09q24bL2qwtlx0qgOfFrjtUb25HaukazwOlVp7TGeKljOZmhwelVJY8Vv3NvjPFZtxFjtUFIxZ0qlKK1blcZrOmGKaHcpSCo8VNJUJ607AKBTgKaDTgaTExyinYpqmpBSEIBTgtAp4pDEC04ClFLRcLAKeDTKXNAiQGnA1EDTgaAJgacDUINPDUhEwNPBqANTw1ILE4anhqrhqcGpMLE+aXNQhqdupBY6LS2M/hPUraNSZI3WU9ANvB/khrAJrb8GMst1dWMku2O5t2UgEAk9OPfBasAtXhZYvZY7F0enNGf/gUUn+MWduJ9+hSn5Nfc/8Agjs0jGkzSE17pxDHqtKasvVaXvQUVpDVd2qaSq0hpjRHI1VZWqWU1UmamMhmaqczVPK1VJTTIZEx5pUbmonNKjc0EM0bc8itazbpWHbvzWraP0qGho37Vuladu1YdrJ0rTgk6Vm0aI01YYp26qqScU/f71NiifdTgarhqkQ0WC5YSrEa1Xi5q7AucVSQXHLHkdKesOT0qzFFkVbht89qpRFcoLb+1Srbe1asVr7VYW09qfKK5ifZz6Uhg9q3Tae1RPa47VLQzF8rmkKYFaclvjtVeWLArNopGbIMVCxq3MuKqSVLRSI2NMNKxpuaTKRG4pm2pW5pKlloWBea1LNRkVnQ8GtK0PSki7mzaKMCtSADFZFs+AKvxTYHWrSBsunAFV7gjFMacY61XnnGOtNom5UvSMGsW7YZNaF7NweaxbqXJPNZSQJkEjfNSq1V3k+alD+9c8kVcvxPUm+qUb1J5lZ8o7nuCiqPiP8A5B6f9dR/I1cU1S8RH/iXp/11H8jXp8Zf8iTE/wCH/I5spX+2U/U6KDrV2PpVKCraGvXqnPAkY1XkapJG4qrM9cE2bJDJHqtLJSTSe9U5pa45yKUB8svvVWWX3qOWX3qrLL71ySkbQgJcy8Hmse9m681aupeDzWLfTdeaI6m6VilfTdeaw72brVy9m681iXcvXmuqESrle4k61Qmenzyc9aqSPXXBESY12qM0M1NJrUxkI3SoXYU924qtK9UkZNjZXqpLJ70s0nvVKaX3qlEnmCWT3qpK/vSSy+9VZJKtRFzD2fNPjNVd/vUkbVdibmjC1W4jWdC1W4nqGhmhEanU1RierKNUMpFgUuKjBp4qGWKBTgKQUoqRMetPjHNRipYvvVSM5F22XJFbNjFnFZVmORW9p68iqM2atjBnHFblna5A4qlp0fSuisIhxxTEFvZ5A4q0tlx0rQtYRgcVdWAY6UXHY5+SzwOlUbq1wDxXUTQj0rNu4hg8VLA5G9gxnisW7ixmurv4xzXP36YzSA5q9TGaybgcmty/HWsW5HJpoZQl61AxqxNVV+tWgHBqXdUWaQtSaBk6tUgaqitUitSsIshqkU1VVqlVqVgJwaXPvUYNLmkO5JmjNMzRmgVyQGnA1FmnA0ASA04GogaUGkMmDU4NUINKDSFYnDU4NUAalDUgLAalDVAGpwalYDY8L3Cwa/Zu4JBfZx6sCo/U03xHE8Gu3kblSTKX49G+YfoazYJ3gmSaJtrxsGU4zgg5Fb/jyNBq0VzCuY7iBW8wHKuRkcHp029Pb1r5+t+5zunN7VKco/OLUl+En/SO6Hv4OS/lkn96t+iMIGlzUQal3V75xCuary1IzVDIaAK8lVZasyVVlpoaKsxqlMatzGqUxpoZWlaqspqxLVWSqsSyFjQp5pH60i9adiGW4G5rTtXxisqE1et2xik0CNu2k6VowSVh28nStCCTpUNFo2I5OKlD1nRSe9TrJU2KLqvU0TVRR6swtzSsBpW9alqucVlWp6VsWXamkK5p2sWcVpW0GccVWshnFbNnH0qkhCwWvtVtLTjpVq2iHHFXUhGOlVYaMh7X2qtNbe1b8kQx0qnPGPSpaGc9PBjPFZ9xHjNb90gGaybxetZNDMO5XrWfN1rUuh1rMuOpqGUVXNMJpzmoyakdxc0E0zNGalopMmiPNXYGxWdGasxPihIu5sRTYFWFuMDrWSsuBT/P461aC5pPc+9VprnjrVGSf3qvJNnvQybk11PkdazZ3yadNLmqrkms5DuMJJanqKaF5qdFNYtDuOjFSUsaGpfLOOlKwrntStVPXzmwT/roP5Gplbmq2uHNkn/XQfyNdnGT/wCETE/4f8i8shbF0/U6WA1ZVqpW5qwG4r16pxqNh8r8VRuJOtTTNxWdcv1rhmjaKIp5evNUZ5qLmXrzWbcTe9cVSJ0wiTSzVWlmqtJNz1qvLNxXJKJuoi3c3B5rEvpuvNW7ubg1iXs3XmtacBS0Kl5L15rGupOTVq7l681lXMnXmu2EDNyIppKqu/NJLJzVV5PetlEhssFhTWeqxkpjScdatIykyWWTAqlNLRNL71Rnl962jE55MJ5feqU0nvRNJ71UketFEjmCSSoGekkeoS3NOwrkwapojVRTzVmHNDGi7CeatxVUhFXYQTWbLRZhFW0FQQrVuNazZqkKoqVRQq04CoLsKBR0oFDUrCaCpYTzUGalhPNWkYyNaz7Vv6d2rnbNuRW7p79KDNnV6b2rpdPxgVymmSDjmul0+UYHNJsDorUDAq6oGKzLWYYHNXVmGOtFxiT4xWXeYwavTyjB5rMvJBg0gMXUSOa5zUD1re1B+tc7ft1oCxh3561i3R5Na98eTWNcnk1SHYozGqshqzMapymqQDS1NLUxmphanYlkoapFaqwapFaiwrllWqZDVRGqxGaloCyppc1Gpp2aQx+aM02jNIB4NLmmZpc0APBpQaYDS5pASA0oNR5pc0mMkzRmmZozSAlDUoaos0ZpCsTBq6fxAftXg/R777nlZg2dc8Yzn/tn09/auTzXU6SftvgPUrYfvZraUSqrf8s04JIJ4HAk6e/rXz+e/upYbE/yVIpvsp3g/LqtTvwXvKpT7xf3rX9DnA1LuqHdSbq9+xwkpao3amlqYxosA2Q1m6pK8UQaNsEtjp7Gr8hrM1c5hX/f/oapLUZQa4mPV/0FMZ2PU02itLIQhUHqKaYYz1X9afRTArXMMawsyrgjHf3qoBV+7/492/D+dUgKLCY+M1bhbFU1qeM0rEmlC/Sr0MlZMTVchek0UjWhk96so9ZkL1bjaoaGX42q1C3NZ8TVehSTAOxsHvg1DQGpaN0rasW6VgWxZcZBFatpOi4y6j6mgDqLFulb1kRxXJWd9bLjdcRD6uK2bPVbFcbr22H1lX/GqQHWWxGBV6MjFc9p+p2
